services:
  backend:
    build:
      context: .
    image: pizza-backend 
    container_name: pizza-backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16.9-bookworm
    container_name: pizza-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: pizzadb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
